# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatur', '0002_album_album_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp1', models.FloatField()),
                ('temp2', models.FloatField()),
                ('temp3', models.FloatField()),
                ('temp4', models.FloatField()),
                ('hum1', models.FloatField()),
                ('hum2', models.FloatField()),
                ('hum3', models.FloatField()),
                ('hum4', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
